### ISSUE TITLE
API mismatch for Stream.Close()

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#1]
The libp2p stream muxer assumes that when calling `Close()` on a `Stream` that both read and write direction are closed. In QUIC, `Close()` only closes the write direction.

**Comment by whyrusleeping** [comment]
@marten-seemann hrm... does QUIC have any sort of a 'fully close this stream' method?

**Comment by marten-seemann** [comment]
Yeah, kind of. There's the `Reset` method (see https://godoc.org/github.com/lucas-clemente/quic-go#Stream), which kills the stream, but if there's outstanding data, it might not get delivered to the application. In H2/QUIC this is used to cancel stream when you close a browser tab before all requests finished loading.

The clean closing procedure requires both sides to close the stream by calling `Close`, when they're done writing to the channel.

**Comment by Stebalien** [comment]
This should no longer be an issue. In libp2p, streams now have a Close and a Reset method. Close closes the write end nicely, reset kills the stream and drops any in-progress data.

**Comment by marten-seemann** [comment]
Right. Close matches now. Reset is not a perfect match now, but it should work as well.
