### ISSUE TITLE
Filter inbound connections

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#124]
Transports should apply the "address filters", either directly on all incoming packets or, at least, on the initial handshake packets. Applying them on all incoming packets could be a performance hit at the moment as the filter is _very_ unoptimized.

The transport can get a copy of the filter set by accepting a `*github.com/libp2p/go-maddr-filter.Filters` in the constructor.

**Comment by marten-seemann** [comment]
The easiest solution will probably be to apply the filter to all [Long Header](https://tools.ietf.org/html/draft-ietf-quic-invariants-07#section-4.1) packets.
