### ISSUE TITLE
reuse code from go-libp2p-tls

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#18]
Given that QUIC is using the standard golang TLS config type, it would be awesome if we could extract this code out into a new library and then re-use the same handshake for TLS over TCP. Something like:

```go
type Identity tls.Config

func NewIdentity(privKey ic.PrivKey) (*Identity, error) { return generateConfig(privKey) }

// for dialing
func (i *Identity) ConfigForPeer(remote ic.PubKey) (*tls.Config, error) {
  // clone the config and set the validator.
}

func KeyFromChain([]*x509...) (ic.PubKey, error) { ... }
```

(and any other useful helper functions you can think of)

**Comment by marten-seemann** [comment]
I like this idea. I thought about that before, but decided to leave this code as part of the QUIC package for now, since QUIC provides us with an easy way to roll out new versions of the handshake protocol. We’ll have to solve that separately if we want to reuse this code.

**Comment by marten-seemann** [comment]
Sure!

**Comment by carsonfarmer** [comment]
What's the latest on this work? We're very interested in https://github.com/libp2p/go-libp2p-quic-transport/issues/60.

**Comment by raulk** [comment]
I believe go-libp2p-tls is ready. We need to update go-libp2p-quic-transport to use it. Is that correct, @marten-seemann?

**Comment by Stebalien** [comment]
See https://github.com/libp2p/go-libp2p-quic-transport/issues/60#issuecomment-507524509. Basically, hard to integrate our quic library as-is.
