### ISSUE TITLE
failing hole punching test

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#213]
```
• Failure [5.530 seconds]
Connection
/home/runner/work/go-libp2p-quic-transport/go-libp2p-quic-transport/conn_test.go:28
  hole punches [It]
  /home/runner/work/go-libp2p-quic-transport/go-libp2p-quic-transport/conn_test.go:367

  didn't expect to accept any connections

  /home/runner/work/go-libp2p-quic-transport/go-libp2p-quic-transport/conn_test.go:380

  Full Stack Trace
  github.com/libp2p/go-libp2p-quic-transport.glob..func2.12.1(0xc00003b7a0, 0xe83860, 0xc000310050)
  	/home/runner/work/go-libp2p-quic-transport/go-libp2p-quic-transport/conn_test.go:380 +0xcc
  created by github.com/libp2p/go-libp2p-quic-transport.glob..func2.12
  	/home/runner/work/go-libp2p-quic-transport/go-libp2p-quic-transport/conn_test.go:376 +0x3ed
------------------------------

**Comment by marten-seemann** [comment]
Weirdly, this now stopped failing locally (on OSX), but now fails randomly on CI. This won't make debugging easier.

**Comment by Stebalien** [comment]
AH! I have a guess.

We now shut down the transport as of https://github.com/libp2p/go-libp2p-quic-transport/pull/216. Maybe we need to _block_ until this finishes?

**Comment by marten-seemann** [comment]
> We now shut down the transport as of #216. Maybe we need to block until this finishes?

We already do that, don't we: https://github.com/libp2p/go-libp2p-quic-transport/blob/8272e16ba45106c3a9f6357fe27c1a930c99e552/reuse.go#L74-L86

**Comment by Stebalien** [comment]
Hm. You're right. I was thinking about https://github.com/lucas-clemente/quic-go/blob/89061486820236ffe76c3770d04fd455f5455251/closed_session.go#L49-L58, but that doesn't keep the socket open.

I have no idea. We're using random ports anyways...
