### ISSUE TITLE
think about certificate expiry

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#22]
Certificates are currently valid for 30 days.

**Comment by marten-seemann** [comment]
This determines how long a node can run and use QUIC without being rebooted. I don't see a lot of reasons to not make this a long time (half a year?). @Stebalien and @whyrusleeping, wdyt?

**Comment by whyrusleeping** [comment]
Yeah, half a year or more seems fine to me. What would the drawbacks of making it longer be?

**Comment by Stebalien** [comment]
Well, in theory we could rotate the keys while online. However, that's probably non-trivial to implement.
