### ISSUE TITLE
Handshake Design

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#3]
## Design Rationale

This is based on the discussion in https://github.com/libp2p/specs/issues/37.

This document describes how two libp2p peers authenticate each other over QUIC. Note that we can use the same handshake not only for QUIC, but for any connection that uses TLS. It works with TLS 1.2 as well as TLS 1.3.

At initialisation, each peer generates a certificate chain consisting of two certificates:

1. a root certificate from the [libp2p private key](https://godoc.org/github.com/ipfs/go-libp2p-crypto#PrivKey). This is the only step that involves the private key, and consequently *could* be used to run a node that doesn't keep its private key in memory (if we ever decide to remove the getter method from the [`ConnSecurity` interface](https://github.com/libp2p/go-libp2p-net/blob/feat/refactor/interface.go#L42-L54))
2. an ephemeral key, that is supposed to be used for a limited time (currently: for the lifetime of the QUIC transport struct). This key is used to generate another certificate, which is signed by the root certificate.

Remember that in IPFS, the peer ID is derived from the key pair, and a node's identity can be verified by checking that their peer ID [matches](https://godoc.org/github.com/ipfs/go-libp2p-peer#ID.MatchesPublicKey) their public key.

Now each node has a certificate chain consisting of two certificates: 1. the root certificate, tied to the node's private key, and 2. an ephemeral certificate. We use TLS client authentication, so during the handshake each node will learn about the other's certificate chain. 

A client verifies a server by setting the `  tls.Config.VerifyPeerCertificate` callback, which is executed *during* the handshake (as soon as the server's cert chain is received). It does so by

1. parsing the certificate chain presented by the server and checking that it actually consists of 2 certificates
2. verifying that the public key from the root certificate matches the peer ID it intended to dial.

The server request TLS client authentication, but it doesn't run set the `VerifyPeerCertificate` callback. As soon as the TLS handshake completes, it

1. parsing the certificate chain presented by the client and checks that it actually consists of 2 certificates
2. determines the peer ID from the root certificate.

## Open Issues

- When the client sends an invalid cert chain (e.g. a chain that only contains one certificate), the server will not abort the handshake (since it only parses the cert chain after the handshake completes), but close the connection immediately after accepting. For the client this will look like the server first accepted the connection, and then closed it shortly afterwards. If we deem this unacceptable, we'd have to parse the cert chain twice (once using the `VerifyPeerCertificate` callback, and once after the handshake completes).

-  Do we need to version this? For example, if we ever want to change the length of the certificate chain to 3, this handshake would fail. We can't really negotiate a handshake protocol here, since authentication happens so early during connection establishment.

**Comment by whyrusleeping** [comment]
Overall this sounds great! reading over it, it seems correct to me. I definitely would like for someone more crypto-knowledgable than myself to think about it (Hey @FiloSottile, could I call in a quick favor here?).

On your open questions:

> For the client this will look like the server first accepted the connection, and then closed it shortly afterwards.

I think this is probably acceptable. The client is the one sending a bad cert chain, and the client is the one being inconvenienced by this. It's definitely a little weird for us to send bad data, then have it appear to work for a short time though... 

> Do we need to version this?

What options do we have for versioning things? are there any header-like fields we can set in the handshake that would allow us to not fail weirdly?

**Comment by Stebalien** [comment]
> The server request TLS client authentication, but it doesn't run set the VerifyPeerCertificate callback. As soon as the TLS handshake completes, it

Any reason *not* to do this inline? It shouldn't be an issue, just curious.

**Comment by marten-seemann** [comment]
@Stebalien:
A server can run multiple handshakes concurrently, so by parsing the chain in the `VerifyPeerCertificate` callback, you'd learn the peer ID, but you wouldn't be able associate it with a connection accepted later on.
We *can* parse the certificate chain once in `VerifyPeerCertificate` and check that it is has the right length and is properly signed, but we'd have to do it again after the handshake completes, in order to find out the peer ID.

I'm beginning to think that this is the thing we *should* do. It's a little bit more CPU load for the server, but parsing a chain of two certificates should still be a lot cheap compared with running the complete TLS handshake. A consistent behaviour in the error case might save us a lot of debugging work in the future.

**Comment by Stebalien** [comment]
I see. We should avoid doing the crypto twice however, I'm ambivalent about parsing the chain twice. While it may make debugging easier, I'm fine verifying everything after the fact.

**Comment by marten-seemann** [comment]
@Stebalien: I just benchmarked this. Verifying the certificate chain is a lot cheaper than I thought, it's just parsing the certificates (i.e. `[][]byte` => `[]*x509.Certificate`). I'll run the full check twice for now. We can still change this later, but at this moment, I'd like to err on the safe side.

**Comment by marten-seemann** [comment]
@whyrusleeping:

> > Do we need to version this?
>
> What options do we have for versioning things? are there any header-like fields we can set in the handshake that would allow us to not fail weirdly?

Our requirement is that we can present a different certificate chain based on the handshake version (consider again the example the case where we decide that we want to present a cert chain consisting of 3 certificates instead of 2).
The Go standard library TLS implementation doesn't have the API to set the certificate chain based on an arbitrary value sent earlier during the handshake. However, this is just an API problem. In TLS 1.3, both the Client Hello and the Server Hello message (which are the first message sent by client and server, respectively) contain a list of TLS extensions. We could define our own libp2p TLS extension that would contain a list of support handshake protocol versions, and then make the certificate chain selection dependent on this. Since I'm not using the Go standard library TLS implementation anyway, I might be able to implement something along these lines. I'd just have to come up with a clean API for this in quic-go.

For now there's an easier solution though: We can just use a new QUIC version number, which will result in a dial failure (and a fallback to TCP) if there's a version mismatch. Since the protocol is evolving quite fast, I'll do this from time to time anyway, so this is not a problem we need to solve within the next half a year or so. Once the protocol stabilises and becomes QUIC v1 we might want to implement a more sophisticated solution as outlined above.

**Comment by whyrusleeping** [comment]
Sounds good to me. The libp2p TLS extension seems like the right way to do this longer term, but the blunt 'bump the quic version' approach seems perfectly acceptable for now
