### ISSUE TITLE
vendor quic-go

### ISSUE THREAD

**Issue by marten-seemann** [libp2p/go-libp2p-quic-transport#41]
We should actually use vendoring for quic-go. This will massively increase the size of this repo, but make installing this package without gx possible.

**Comment by anacrolix** [comment]
What's required to do this?

**Comment by marten-seemann** [comment]
The fix for this is blocked by CI issues. I'd like to use CircleCI for this repository, and I'd appreciate if any of the owners could add that CI.

**Comment by Stebalien** [comment]
Is travis not working? I ask because using different CIs for different repos is a real pain (and we're already using travis + jenkins everywhere).

**Comment by anacrolix** [comment]
Have you considered using go.mod instead of vendoring?

**Comment by Stebalien** [comment]
We still want to be compatible with `go get` for now.

**Comment by marten-seemann** [comment]
Outdated since we're now using go mod.
