### ISSUE TITLE
Warnings/Errors while using the library

### ISSUE THREAD

**Issue by tomgie** [libp2p/go-libp2p-quic-transport#51]
While using this library in IPFS I am getting these current errors

../../libp2p/go-libp2p-quic-transport/stream.go:15:31: s.Stream.CancelRead(0) used as value
../../libp2p/go-libp2p-quic-transport/stream.go:18:29: s.Stream.CancelWrite(0) used as value
../../libp2p/go-libp2p-quic-transport/transport.go:22:62: undefined: quic.VersionMilestone0_10_0

**Comment by marten-seemann** [comment]
Please make sure that you're using gx to install, it contains the right version of quic-go.
