### ISSUE TITLE
Update quic-go

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#53]
To fix the deadlock. See: https://github.com/ipfs/go-ipfs/issues/6168.

Ideally, we'd get this into the impending go-ipfs release.

**Comment by marten-seemann** [comment]
What's the timeline for the next go-ipfs release? I could cut a new quic-go release right away, but it makes sense to delay this until shortly before the release, to get as many new quic-go changes in as possible.

**Comment by Stebalien** [comment]
Approximately now.

**Comment by marten-seemann** [comment]
Ok, working on it. Will take a couple of hours.

**Comment by Stebalien** [comment]
Thanks!
