### ISSUE TITLE
Panic when running with quic enabled

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-quic-transport#55]
```
panic: qtls.ClientSessionState not compatible with tls.ClientSessionState

goroutine 1 [running]:
github.com/lucas-clemente/quic-go/internal/handshake.init.0()
	/home/ubuntu/go/pkg/mod/github.com/lucas-clemente/quic-go@v0.11.0/internal/handshake/unsafe.go:20 +0x113
```

**Comment by marten-seemann** [comment]
Which go version?

**Comment by vyzo** [comment]
it's go1.11 in the relays, I probably should upgrade that.

**Comment by marten-seemann** [comment]
Yes, this is expected. quic-go requires Go 1.12.x, since Go 1.11 doesn't have TLS 1.3 support.

**Comment by vyzo** [comment]
Can't this be turned into a compile-time check? It's a nasty surprise to compile just fine and then immediately panic when run.

**Comment by marten-seemann** [comment]
I could, but I don't think I want to spend time on outdated Go versions (and then re-releasing everything).
