### ISSUE TITLE
QUIC transport constructor fails with ed25519 keys

### ISSUE THREAD

**Issue by vyzo** [libp2p/go-libp2p-quic-transport#60]
Trying to bring up some relays using ed25519 keys, and I run into this:
```
May 01 18:14:27 ip-172-31-47-2 relay.sh[13132]: 2019/05/01 18:14:27 transport constructor github.com/libp2p/go-libp2p-quic-transport.NewTransport failed: unsupported key type for TLS
```

**Comment by vyzo** [comment]
So basically we can't use QUIC with ed25519 keys.

**Comment by Stebalien** [comment]
We need to switch to the new TLS handshake, IIRC.

**Comment by vyzo** [comment]
Is there a quic(k) remedy for this so that we can use it now?

**Comment by Stebalien** [comment]
Not really.

**Comment by xaionaro** [comment]
I've just added a PR: https://github.com/libp2p/go-libp2p-quic-transport/pull/65

But it requires Go1.13

**Comment by Kubuxu** [comment]
Yeah, we need to wait for Go1.13 as they've just introduced ed25519 support in TLS and included ed25519 in standard library.

**Comment by marten-seemann** [comment]
We should probably rather reuse the code from the TLS package (see #18). In addition to code reuse, this will allow us to use all key types. Unfortunately, since QUIC doesn't have a separate `net.Conn` per connection, this is not trivial though.

**Comment by xaionaro** [comment]
> We should probably rather reuse the code from the TLS package (see #18). In addition to code reuse, this will allow us to use all key types.

I've added a comment in the PR: https://github.com/libp2p/go-libp2p-quic-transport/pull/65#issuecomment-507534657
