### ISSUE TITLE
Quic-go changed interface, installing now fails

### ISSUE THREAD

**Issue by justino10950** [libp2p/go-libp2p-quic-transport#61]
go get now fails with

`# github.com/libp2p/go-libp2p-quic-transport
..\..\..\..\..\github.com\libp2p\go-libp2p-quic-transport\listener.go:68:24: cannot use err (type error) as type string in argument to sess.CloseWithError`

Should the passed parameter be changed to string?

**Comment by marten-seemann** [comment]
You need to use Go mod, otherwise Go will try to pull in the latest version of quic-go.
