### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by Stebalien** [libp2p/go-libp2p-quic-transport#76]
We need to cut a quic release and bubble it up to go-libp2p. However, we've made some significant changes (protocol breaking) so I'd rather not just go ahead and do this myself.

**Comment by marten-seemann** [comment]
I'd like to wait with this for about 2 weeks or so. quic-go v0.12.0 is pretty old already, and there are some known bugs that will be fixed in the next version.

**Comment by jsign** [comment]
@marten-seemann, is `v0.12.1` what was missing to make this possible?

**Comment by marten-seemann** [comment]
@jsign v0.12.1 is the same as v0.12.0, since apparently there was a problem with Google's module caching (see https://github.com/lucas-clemente/quic-go/issues/2129).

**Comment by jsign** [comment]
Oh. Do you have a feeling about when the next version will be tagged?
Context: Interested in PR that allows ed25519 keys (instead of only RSA) eventually bubbles up to a tagged version of `go-ipfs`.

**Comment by marten-seemann** [comment]
I want to fix https://github.com/lucas-clemente/quic-go/issues/2045 first, then I'll cut the next release.
