### ISSUE TITLE
Ed25519 Keys Are Incompatible

### ISSUE THREAD

**Issue by postables** [libp2p/go-libp2p-quic-transport#80]
Attempting to use this transport with a libp2p node using ed25519 keys results in the following error:

```
 transport constructor github.com/libp2p/go-libp2p-quic-transport.NewTransport failed: unsupported key type for TLS
```

Go version: 1.13.1
go-libp2p-quic-transport: v0.1.1

**Comment by marten-seemann** [comment]
This should work with `master`, but we haven't cut a release that includes #67 yet.
